spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;user=sa;password=test@1234;database=todo_db;encrypt=false
    username: sa
    password: test@1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

server:
  port: 6969